//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HRMResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HRMResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.HRMResources", typeof(HRMResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string Createanaccount {
            get {
                return ResourceManager.GetString("Createanaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create group.
        /// </summary>
        public static string CreateGroup {
            get {
                return ResourceManager.GetString("CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create group new.
        /// </summary>
        public static string CreateGroupNew {
            get {
                return ResourceManager.GetString("CreateGroupNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email has been registered in the system, please return to the login page!.
        /// </summary>
        public static string EmailExistsErr {
            get {
                return ResourceManager.GetString("EmailExistsErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter group name.
        /// </summary>
        public static string EnterGroupName {
            get {
                return ResourceManager.GetString("EnterGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or mobile number!.
        /// </summary>
        public static string Login_Err {
            get {
                return ResourceManager.GetString("Login_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm password must match..
        /// </summary>
        public static string Passwordandconfirmpasswordmustmatch {
            get {
                return ResourceManager.GetString("Passwordandconfirmpasswordmustmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email.
        /// </summary>
        public static string Pleaseenteravalidemail {
            get {
                return ResourceManager.GetString("Pleaseenteravalidemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid mobile.
        /// </summary>
        public static string Pleaseenteravalidmobile {
            get {
                return ResourceManager.GetString("Pleaseenteravalidmobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password.
        /// </summary>
        public static string PleaseEnterPassword {
            get {
                return ResourceManager.GetString("PleaseEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input email or mobile.
        /// </summary>
        public static string Pleaseinputemailormobile {
            get {
                return ResourceManager.GetString("Pleaseinputemailormobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input password.
        /// </summary>
        public static string Pleaseinputpassword {
            get {
                return ResourceManager.GetString("Pleaseinputpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        public static string Resend {
            get {
                return ResourceManager.GetString("Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search contacts &amp; groups.
        /// </summary>
        public static string Searchcontactsandgroups {
            get {
                return ResourceManager.GetString("Searchcontactsandgroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a contact or group to start chatting.
        /// </summary>
        public static string Selectacontract {
            get {
                return ResourceManager.GetString("Selectacontract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Members.
        /// </summary>
        public static string SelectMembers {
            get {
                return ResourceManager.GetString("SelectMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending...!.
        /// </summary>
        public static string Sending {
            get {
                return ResourceManager.GetString("Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Signin {
            get {
                return ResourceManager.GetString("Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signin with.
        /// </summary>
        public static string Signinwith {
            get {
                return ResourceManager.GetString("Signinwith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup error.
        /// </summary>
        public static string Signuperror {
            get {
                return ResourceManager.GetString("Signuperror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup with.
        /// </summary>
        public static string Signupwith {
            get {
                return ResourceManager.GetString("Signupwith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup with Email.
        /// </summary>
        public static string SignupwithEmail {
            get {
                return ResourceManager.GetString("SignupwithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup with Mobile.
        /// </summary>
        public static string SignupwithMobile {
            get {
                return ResourceManager.GetString("SignupwithMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
    }
}
