/**
 * For theme Gull
 */
document.write('<script type="text/javascript" src="/Content/theme/gull/jquery-3.3.1.min.js"><\/script>');
document.write('<script type="text/javascript" src="/Content/theme/gull/bootstrap.bundle.min.js"><\/script>');

document.write('<script type="text/javascript" src="/Content/libs/perfect-scrollbar/perfect-scrollbar.min.js"><\/script>');
document.write('<script type="text/javascript" src="/Content/libs/pace/pace.min.js"><\/script>');
document.write('<script type="text/javascript" src="/Content/libs/toastr/toastr.js"><\/script>');

document.write('<script type="text/javascript" src="/Content/theme/gull/script.js"><\/script>');
//document.write('<script type="text/javascript" src="/Content/theme/gull/sidebar.large.script.js"><\/script>');
//document.write('<script type="text/javascript" src="/Content/theme/gull/customizer.script.js"><\/script>');